FROM node:24-alpine as build
WORKDIR /app
COPY package* .
RUN npm install
COPY . .
# RUN npm run build
ARG VITE_REACT_API_URL
ENV VITE_REACT_API_URL=${VITE_REACT_API_URL}

# FROM nginx:alpine
# COPY --from=build /app/build /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 8082
CMD [ "npm","run","dev" ]